# TestPage class will wrap MartaTestPage class generated by Marta
# Methods that are not defined here will be taken from class generated by Marta
class MyTestPage < MartaTestPage
  def form_fill(name: 'somebody', story: 'nostory', watir_radio: true,
                language: 'Ruby', browser: 'Chrome', how_happy: '1',
                item1: '5', item2: '3')
    # name_field is MartaTestPage.name_field.
    # Marta will ask about it in learning mode
    name_field.set name
    story_area.set story
    # selenium radio button was never defined.
    # So selenium.set will cause an error... But in learn mode you can define it
    # Or you can:
    # self.method_edit('selenium')
    watir_radio ? watir.set : selenium.set
    # These values was alredy set to some values at page\class defining stage
    @lang = language
    @happy = how_happy
    @i1 = item1
    @i2 = item2
    dropbox.select browser
    # language_checkbox, how_happy_element, item1_element and item2_element are
    # defined as dependant of related variables. For example if @lang == 'Java'
    # language_checkbox will be an element <input... value='Java'>
    language_checkbox.set
    how_happy_element.set
    item1_element.set
    item2_element.set
    send_button.click
  end
end
