# TestPage class will wrap MartaTestPage class generated by Marta
# Methods that are not defined here will be taken from class generated by Marta
class MyTestPage < MartaTestPage
  def form_fill(some: 'thing', selection: 'Z', confirmed: true,
                r_selection: (rand(3)+1).to_s)
    # some_field is MartaTestPage.some_field.
    # Marta will ask about it in learning mode
    some_field.set some
    # We will choose radio dynamically. Note:
    # the variable @r_select is defined at the page creation stage
    @r_select = r_selection
    dynamic_radio.set
    dropbox.select selection
    dummy_checkbox.set if confirmed
    first_button.click
  end
end
